services:
  nfo-generator:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_BASE_PATH: ${VITE_BASE_PATH:-/}
    ports:
      - '8787:8787'
    environment:
      HOST: '0.0.0.0'
      PORT: '8787'
      BASE_PATH: ${BASE_PATH:-/}
      MEDIAINFO_LANGUAGE: ${MEDIAINFO_LANGUAGE:-fr}
      MEDIAINFO_OUTPUT_PROFILE: 'standard'
